string DUBINS_SERVICE = 'mission/dubins_service'
string UTM_LATLON_CONVERSION_SERVICE = 'mission/utm_latlon_conversion_service'

string MISSION_COMPLETE_TOPIC = 'mission/complete'
string MISSION_CONTROL_TOPIC = 'mission/mission_control'
string BT_COMMAND_TOPIC = 'mission/bt_command'
string BT_TIP_TOPIC = 'mission/bt_tip'
string BT_LAST_WP_TOPIC = 'mission/last_wp'

string GOTO_WP_ACTION = 'mission/goto_wp_action'