version: "3"
services:
  broker:
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - "./mosquitto:/mosquitto"
    networks:
      - localnet
    ports:
      - "1884:1883"
  node-red:
    depends_on:
      - broker
    image: nodered/node-red:latest
    restart: always
    volumes:
      - "./node-red:/data"
    user: "0"
    networks:
      - localnet
    ports:
      - "1880:1880"
  mapserver:
    image: camptocamp/mapserver:latest
    restart: always
    environment:
        - PROJ_DEBUG=5
    volumes:
        - "./mapserver/sweden.map/:/etc/mapserver/sweden.map:ro"
        - "/home/azureuser/swe_bathy/:/mapdata/sweden/:ro"
    networks:
      - localnet
    ports:
      - "1881:80"
  mapproxy:
    image: ghcr.io/mapproxy/mapproxy/mapproxy:1.16.0-nginx
    restart: always
    volumes:
        - "./mapproxy/:/mapproxy/config/"
    networks:
        - localnet
    ports:
        - "1889:80"
       
networks:
  localnet:

# PORTS: <HOST>:<CONTAINER>
#Volume mapping allows all configuration and data to be stored on the host file system, or elsewhere on the network. Configuration of Node-RED is assumed to be in folder node-red, relative to the compose file location, and Mosquitto configuration and data is assumed to be under folder mosquitto.
#The compose file defines a private bridge network called localnet. Code running in containers can use service names specified in compose file as host names. In the Node-RED container, broker will resolve to IP address of the container running Mosquitto.
# Port mapping allows container services to be available to applications running on the host or host network. A browser running on the host can access Node-RED at http://localhost:1880. Another machine on the same network can access it at http://<ip address of host>:1880. Mosquitto can be accessed at port 1883 on the host network.
# default mapserver port is 8080 (or 80 if root) inside the container, map that to sth free outside (1886?)
