FROM ros:humble-ros-base-jammy

# we want the familiar bash for everything, not sh.
# this makes source-ing work
SHELL ["/bin/bash", "-c"]

# update things
RUN apt update && apt upgrade -y

# package managers and such...
RUN apt install -y python3-pip apt-utils ros-dev-tools

# this version of setuptools doesn't have the annoying warnings...
RUN pip install --no-input setuptools==58.2.0

WORKDIR /home

# clone the base smarc2 dir and make the colcon ws while at it
RUN mkdir -p colcon_ws/src

# use an arg to force docker to build from here, even with cache enabled.
# useful to git pull every build!
ARG DATE_STAMP
RUN cd colcon_ws/src && git clone https://github.com/KKalem/smarc2

# make colcon behave
RUN mkdir /home/.colcon/ \
&&  cp /home/colcon_ws/src/smarc2/docker/defaults.yaml /home/.colcon/

WORKDIR /home/colcon_ws/src/smarc2

# get the submodules needed for core
RUN scripts/get-submodules.sh external

# install deps
WORKDIR /home/colcon_ws
RUN rosdep update \
&&  ./src/smarc2/scripts/rosdep_install_from_src.sh

# no bashrc in dockerfiles, so we source and build in the same run
RUN source /opt/ros/humble/setup.bash \
&&  colcon build


# this sources the setup.bash by default
ENTRYPOINT [ "/ros_entrypoint.sh" ] 


